# Use this file to templatize your application's native configuration files.
# See the docs at https://www.habitat.sh/docs/create-packages-configure/.
# You can safely delete this file if you don't need it.
interval = 300
splay = 30
splay_first_run = 0
run_lock_timeout = 300
log_level = "warn"
env_path_prefix = "/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin"
ssl_verify_mode = ":verify_none"

[automate]
enable = true
server_url = "https://<AUTOMATE_URL>/data-collector/v0/"
token = '<TOKEN>'